version: '3'
services:
  mysql:
    restart: always
    image: mysql:5.7.18
    container_name: todo-list-mysql
    volumes:
      - ./mydir:/mydir
      - ./datadir:/var/lib/mysql
      - ./conf/my.cnf:/etc/my.cnf
      - ./source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=todo-lisp-pass"
      - "MYSQL_DATABASE=todo-list"
      - "TZ=Asia/Shanghai"
    ports:
      # 使用宿主机的3306端口映射到容器的3306端口
      # 宿主机：容器
      - 4005:3306
